# Generated by Django 4.1 on 2022-09-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listoffilm',
            name='release_date',
            field=models.DateField(),
        ),
    ]
