# Generated by Django 4.1 on 2022-09-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_alter_listoffilm_release_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListOfFilm',
            new_name='MyWatchList',
        ),
    ]
